"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type Segment = { start: number; end: number; text: string };
type Style = { fontSize: number; position: "bottom" | "center" | "top"; background: boolean };

type Language = { code: string; label: string };

const LANGUAGES: Language[] = [
  { code: "auto", label: "Auto Detect" },
  { code: "en", label: "English" },
  { code: "ta", label: "தமிழ் (Tamil)" },
  { code: "hi", label: "हिन्दी (Hindi)" },
  { code: "te", label: "తెలుగు (Telugu)" },
  { code: "ml", label: "മലയാളം (Malayalam)" },
  { code: "kn", label: "ಕನ್ನಡ (Kannada)" },
  { code: "bn", label: "বাংলা (Bengali)" },
  { code: "mr", label: "मराठी (Marathi)" },
  { code: "gu", label: "ગુજરાતી (Gujarati)" },
  { code: "pa", label: "ਪੰਜਾਬੀ (Punjabi)" }
];

export default function CaptionStudio() {
  const [video, setVideo] = useState<File | null>(null);
  const [url, setUrl] = useState("");
  const [segments, setSegments] = useState<Segment[]>([]);
  const [currentTime, setCurrentTime] = useState(0);
  const [status, setStatus] = useState("");
  const [busy, setBusy] = useState(false);
  const [language, setLanguage] = useState("en");
  const [style, setStyle] = useState<Style>({ fontSize: 28, position: "bottom", background: true });
  const videoRef = useRef<HTMLVideoElement>(null);

  useEffect(() => () => { if (url) URL.revokeObjectURL(url); }, [url]);

  const active = useMemo(
    () => segments.find((s) => currentTime >= s.start && currentTime <= s.end)?.text ?? "",
    [segments, currentTime]
  );

  const selectedLanguage = LANGUAGES.find((item) => item.code === language)?.label ?? "English";

  async function transcribe() {
    if (!video) return;
    setBusy(true);
    setStatus(`Sending video to Gemini for ${selectedLanguage} captions…`);

    try {
      const form = new FormData();
      form.append("video", video);
      form.append("language", language);
      const res = await fetch("/api/transcribe", { method: "POST", body: form });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Caption generation failed");
      setSegments(data.segments || []);
      setStatus(`Done — ${data.segments?.length || 0} ${selectedLanguage} caption segments generated by Gemini`);
    } catch (e: any) {
      setStatus(e.message || "Something went wrong");
    } finally {
      setBusy(false);
    }
  }

  function downloadSrt() {
    const srt = segments.map((s, i) => {
      const tc = (n: number) => {
        const ms = Math.round(n * 1000);
        const h = Math.floor(ms / 3600000);
        const m = Math.floor((ms % 3600000) / 60000);
        const sec = Math.floor((ms % 60000) / 1000);
        const milli = ms % 1000;
        return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(sec).padStart(2, "0")},${String(milli).padStart(3, "0")}`;
      };
      return `${i + 1}\n${tc(s.start)} --> ${tc(s.end)}\n${s.text}\n`;
    }).join("\n");

    const a = document.createElement("a");
    a.href = URL.createObjectURL(new Blob([srt], { type: "text/plain;charset=utf-8" }));
    a.download = `captions-${language}.srt`;
    a.click();
  }

  function choose(file: File) {
    if (!file.type.startsWith("video/")) return;
    if (url) URL.revokeObjectURL(url);
    setVideo(file);
    setUrl(URL.createObjectURL(file));
    setSegments([]);
    setCurrentTime(0);
    setStatus("");
  }

  return (
    <main>
      <nav className="nav"><div className="logo">Caption<span>AI</span></div><div className="pill">GEMINI AI VIDEO CAPTIONS</div></nav>
      <section className="hero">
        <div>
          <p className="eyebrow">VIDEO → GEMINI AI → MULTILINGUAL CAPTIONS</p>
          <h1>Make every word<br /><span>easy to follow.</span></h1>
          <p className="lead">Upload a video, choose a language, and Gemini creates synchronized captions in seconds.</p>
        </div>
        <div className="card">
          {!video ? (
            <label className="drop">
              <div className="uploadIcon">↑</div>
              <strong>Drop your video here</strong>
              <span>or tap to browse • MP4, MOV, WebM</span>
              <input type="file" accept="video/*" onChange={(e) => e.target.files?.[0] && choose(e.target.files[0])} />
            </label>
          ) : (
            <>
              <div className="preview">
                <video
                  ref={videoRef}
                  src={url}
                  controls
                  onTimeUpdate={() => setCurrentTime(videoRef.current?.currentTime ?? 0)}
                />
                {active && <div className={`caption ${style.position}`} style={{ fontSize: style.fontSize, background: style.background ? "rgba(0,0,0,.72)" : "transparent" }}>{active}</div>}
              </div>

              <div className="languagePicker">
                <label htmlFor="caption-language">Caption language</label>
                <select id="caption-language" value={language} onChange={(e) => { setLanguage(e.target.value); setSegments([]); setStatus(""); }} disabled={busy}>
                  {LANGUAGES.map((item) => <option key={item.code} value={item.code}>{item.label}</option>)}
                </select>
                <small>Choose the subtitle language. Auto Detect keeps the language spoken in the video.</small>
              </div>

              <div className="controls">
                <button className="primary" disabled={busy} onClick={transcribe}>{busy ? "Gemini is processing…" : `Generate ${selectedLanguage} captions`}</button>
                {segments.length > 0 && <button onClick={downloadSrt}>Download SRT</button>}
                <button onClick={() => { setVideo(null); setSegments([]); setUrl(""); setStatus(""); }}>Change video</button>
              </div>
              {segments.length > 0 && <div className="editor">
                <h3>Caption style</h3>
                <label>Size <input type="range" min="18" max="54" value={style.fontSize} onChange={(e) => setStyle({ ...style, fontSize: +e.target.value })} /></label>
                <label>Position <select value={style.position} onChange={(e) => setStyle({ ...style, position: e.target.value as Style["position"] })}><option value="bottom">Bottom</option><option value="center">Center</option><option value="top">Top</option></select></label>
                <label><input type="checkbox" checked={style.background} onChange={(e) => setStyle({ ...style, background: e.target.checked })} /> Background</label>
              </div>}
              <p className="status">{status}</p>
            </>
          )}
        </div>
      </section>
      <section className="features">
        <div><b>01</b><h3>Gemini transcription</h3><p>Gemini analyzes the uploaded video and creates timestamped captions in your selected language.</p></div>
        <div><b>02</b><h3>Multilingual preview</h3><p>Preview English, Tamil, Hindi and other supported languages directly over the video.</p></div>
        <div><b>03</b><h3>SRT export</h3><p>Download a standard UTF-8 subtitle file for editing or publishing.</p></div>
      </section>
      <footer>CaptionAI • Gemini API key stays on the server.</footer>
    </main>
  );
}