"use client";

import { upload } from "@vercel/blob/client";
import { useEffect, useMemo, useRef, useState } from "react";

type Segment = { start: number; end: number; text: string };
type Style = { fontSize: number; x: number; y: number; background: boolean };
type Language = { code: string; label: string };

const LANGUAGES: Language[] = [
  { code: "auto", label: "Auto Detect" },
  { code: "en", label: "English" },
  { code: "ta", label: "தமிழ் (Tamil)" },
  { code: "hi", label: "हिन्दी (Hindi)" },
  { code: "te", label: "తెలుగు (Telugu)" },
  { code: "ml", label: "മലയാളം (Malayalam)" },
  { code: "kn", label: "ಕನ್ನಡ (Kannada)" },
  { code: "bn", label: "বাংলা (Bengali)" },
  { code: "mr", label: "मराठी (Marathi)" },
  { code: "gu", label: "ગુજરાતી (Gujarati)" },
  { code: "pa", label: "ਪੰਜਾਬੀ (Punjabi)" }
];

export default function CaptionStudio() {
  const [video, setVideo] = useState<File | null>(null);
  const [url, setUrl] = useState("");
  const [segments, setSegments] = useState<Segment[]>([]);
  const [currentTime, setCurrentTime] = useState(0);
  const [status, setStatus] = useState("");
  const [busy, setBusy] = useState(false);
  const [exporting, setExporting] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [language, setLanguage] = useState("en");
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [style, setStyle] = useState<Style>({ fontSize: 28, x: 50, y: 84, background: true });
  const videoRef = useRef<HTMLVideoElement>(null);
  const previewRef = useRef<HTMLDivElement>(null);

  useEffect(() => () => { if (url) URL.revokeObjectURL(url); }, [url]);

  useEffect(() => {
    const onFullscreenChange = () => {
      setIsFullscreen(document.fullscreenElement === previewRef.current);
    };
    document.addEventListener("fullscreenchange", onFullscreenChange);
    return () => document.removeEventListener("fullscreenchange", onFullscreenChange);
  }, []);

  const active = useMemo(
    () => segments.find((s) => currentTime >= s.start && currentTime <= s.end)?.text ?? "",
    [segments, currentTime]
  );
  const selectedLanguage = LANGUAGES.find((item) => item.code === language)?.label ?? "English";

  async function toggleFullscreen() {
    const preview = previewRef.current;
    if (!preview) return;
    try {
      if (document.fullscreenElement) {
        await document.exitFullscreen();
      } else if (preview.requestFullscreen) {
        await preview.requestFullscreen();
      } else {
        setStatus("Fullscreen mode is not supported by this browser.");
      }
    } catch {
      setStatus("Could not enter fullscreen mode. Please try again.");
    }
  }

  async function transcribe() {
    if (!video) return;
    setBusy(true);
    setUploadProgress(0);
    setStatus("Uploading video directly to secure storage…");

    try {
      const blob = await upload(`captionai/${Date.now()}-${video.name}`, video, {
        access: "public",
        handleUploadUrl: "/api/upload",
        multipart: true,
        onUploadProgress: (event) => {
          setUploadProgress(event.percentage);
          setStatus(`Uploading video… ${Math.round(event.percentage)}%`);
        }
      });

      setStatus(`Video uploaded. Gemini is generating ${selectedLanguage} captions…`);
      const res = await fetch("/api/transcribe", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ videoUrl: blob.url, videoType: video.type || "video/mp4", videoName: video.name, language })
      });

      const contentType = res.headers.get("content-type") || "";
      const raw = await res.text();
      let data: { error?: string; segments?: Segment[] } = {};
      if (contentType.includes("application/json")) {
        try { data = JSON.parse(raw); } catch { data = { error: "The server returned invalid JSON." }; }
      } else if (raw.trim()) data = { error: raw.trim() };

      if (!res.ok) throw new Error(data.error || `Caption request failed with HTTP ${res.status}`);
      if (!data.segments) throw new Error("Gemini returned an unexpected response.");

      setSegments(data.segments);
      setStatus(`Done — ${data.segments.length} ${selectedLanguage} caption segments generated by Gemini.`);
    } catch (e: any) {
      const message = e?.message || "Something went wrong";
      if (/BLOB|token|upload/i.test(message) && !message.includes("Caption generation failed")) {
        setStatus(`Video upload failed: ${message}. Make sure a Vercel Blob store is connected to this project.`);
      } else setStatus(message);
    } finally {
      setBusy(false);
      setUploadProgress(0);
    }
  }

  function downloadSrt() {
    const tc = (n: number) => {
      const ms = Math.round(n * 1000);
      const h = Math.floor(ms / 3600000);
      const m = Math.floor((ms % 3600000) / 60000);
      const sec = Math.floor((ms % 60000) / 1000);
      return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(sec).padStart(2, "0")},${String(ms % 1000).padStart(3, "0")}`;
    };
    const srt = segments.map((s, i) => `${i + 1}\n${tc(s.start)} --> ${tc(s.end)}\n${s.text}\n`).join("\n");
    const blobUrl = URL.createObjectURL(new Blob([srt], { type: "text/plain;charset=utf-8" }));
    const a = document.createElement("a");
    a.href = blobUrl;
    a.download = `captions-${language}.srt`;
    a.click();
    URL.revokeObjectURL(blobUrl);
  }

  function moveCaption(clientX: number, clientY: number) {
    const box = previewRef.current?.getBoundingClientRect();
    if (!box) return;
    const x = Math.max(8, Math.min(92, ((clientX - box.left) / box.width) * 100));
    const y = Math.max(8, Math.min(92, ((clientY - box.top) / box.height) * 100));
    setStyle((s) => ({ ...s, x, y }));
  }

  function startDrag(e: React.PointerEvent<HTMLDivElement>) {
    e.preventDefault();
    e.currentTarget.setPointerCapture(e.pointerId);
    moveCaption(e.clientX, e.clientY);
  }

  function drag(e: React.PointerEvent<HTMLDivElement>) {
    if (e.currentTarget.hasPointerCapture(e.pointerId)) moveCaption(e.clientX, e.clientY);
  }

  async function exportCaptionedVideo() {
    const source = videoRef.current;
    if (!source || !segments.length) return;
    if (!window.MediaRecorder || !HTMLCanvasElement.prototype.captureStream) {
      setStatus("Video export is not supported in this browser. Try the latest Chrome or Edge.");
      return;
    }
    setExporting(true);
    setStatus("Rendering your captioned video in real time… keep this tab open.");
    try {
      const canvas = document.createElement("canvas");
      canvas.width = source.videoWidth || 1280;
      canvas.height = source.videoHeight || 720;
      const ctx = canvas.getContext("2d");
      if (!ctx) throw new Error("Canvas export is unavailable");
      const canvasStream = canvas.captureStream(30);
      const sourceStream = (source as HTMLVideoElement & { captureStream?: () => MediaStream }).captureStream?.();
      if (!sourceStream) throw new Error("This browser cannot capture video audio for export");
      sourceStream.getAudioTracks().forEach((track) => canvasStream.addTrack(track));
      const mimeType = ["video/webm;codecs=vp9,opus", "video/webm;codecs=vp8,opus", "video/webm"].find((type) => MediaRecorder.isTypeSupported(type));
      if (!mimeType) throw new Error("No supported WebM video format was found");
      const chunks: BlobPart[] = [];
      const recorder = new MediaRecorder(canvasStream, { mimeType, videoBitsPerSecond: 6000000 });
      recorder.ondataavailable = (e) => { if (e.data.size) chunks.push(e.data); };
      await source.play();
      source.currentTime = 0;
      await new Promise<void>((resolve, reject) => {
        const cleanup = () => { source.removeEventListener("ended", finish); source.removeEventListener("error", fail); };
        const finish = () => { cleanup(); resolve(); };
        const fail = () => { cleanup(); reject(new Error("Video playback failed during export")); };
        const draw = () => {
          ctx.drawImage(source, 0, 0, canvas.width, canvas.height);
          const segment = segments.find((s) => source.currentTime >= s.start && source.currentTime <= s.end);
          if (segment) {
            const fontPx = Math.max(18, Math.round((style.fontSize / 28) * canvas.height * 0.026));
            ctx.font = `700 ${fontPx}px system-ui, sans-serif`;
            ctx.textAlign = "center";
            ctx.textBaseline = "middle";
            const maxWidth = canvas.width * 0.82;
            const lines: string[] = [];
            let line = "";
            for (const word of segment.text.split(/\s+/)) {
              const next = line ? `${line} ${word}` : word;
              if (ctx.measureText(next).width > maxWidth && line) { lines.push(line); line = word; } else line = next;
            }
            if (line) lines.push(line);
            const lineHeight = fontPx * 1.2;
            const totalHeight = lines.length * lineHeight;
            const cx = (style.x / 100) * canvas.width;
            const cy = (style.y / 100) * canvas.height;
            if (style.background) {
              const bw = Math.min(maxWidth + 32, Math.max(...lines.map((t) => ctx.measureText(t).width)) + 32);
              const bh = totalHeight + 22;
              ctx.fillStyle = "rgba(0,0,0,.72)";
              ctx.beginPath();
              ctx.roundRect(cx - bw / 2, cy - bh / 2, bw, bh, 14);
              ctx.fill();
            }
            ctx.fillStyle = "#fff";
            lines.forEach((t, i) => ctx.fillText(t, cx, cy - totalHeight / 2 + lineHeight / 2 + i * lineHeight));
          }
          if (!source.ended) requestAnimationFrame(draw);
        };
        source.addEventListener("ended", finish, { once: true });
        source.addEventListener("error", fail, { once: true });
        recorder.start(250);
        requestAnimationFrame(draw);
      });
      await new Promise<void>((resolve) => { recorder.addEventListener("stop", () => resolve(), { once: true }); recorder.stop(); });
      canvasStream.getTracks().forEach((track) => track.stop());
      sourceStream.getTracks().forEach((track) => track.stop());
      const blob = new Blob(chunks, { type: mimeType });
      const blobUrl = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = blobUrl;
      a.download = `captioned-${language}.webm`;
      a.click();
      setTimeout(() => URL.revokeObjectURL(blobUrl), 1000);
      setStatus("Done — captioned video downloaded.");
    } catch (e: any) {
      setStatus(e.message || "Video export failed");
    } finally {
      setExporting(false);
      source.pause();
    }
  }

  function choose(file: File) {
    if (!file.type.startsWith("video/")) return;
    if (url) URL.revokeObjectURL(url);
    setVideo(file);
    setUrl(URL.createObjectURL(file));
    setSegments([]);
    setCurrentTime(0);
    setStatus("");
    setStyle({ fontSize: 28, x: 50, y: 84, background: true });
  }

  return (
    <main>
      <nav className="nav"><div className="logo">Caption<span>AI</span></div><div className="pill">GEMINI AI VIDEO CAPTIONS</div></nav>
      <section className="hero">
        <div>
          <p className="eyebrow">VIDEO → GEMINI AI → MULTILINGUAL CAPTIONS</p>
          <h1>Make every word<br /><span>easy to follow.</span></h1>
          <p className="lead">Upload a video, choose a language, and Gemini creates synchronized captions in seconds.</p>
        </div>
        <div className="card">
          {!video ? (
            <label className="drop">
              <div className="uploadIcon">↑</div>
              <strong>Drop your video here</strong>
              <span>or tap to browse • MP4, MOV, WebM • Large videos supported</span>
              <input type="file" accept="video/*" onChange={(e) => e.target.files?.[0] && choose(e.target.files[0])} />
            </label>
          ) : (
            <>
              <div className={`preview ${isFullscreen ? "previewFullscreen" : ""}`} ref={previewRef}>
                <video ref={videoRef} src={url} controls onTimeUpdate={() => setCurrentTime(videoRef.current?.currentTime ?? 0)} />
                {active && <div className="caption draggable" onPointerDown={startDrag} onPointerMove={drag} style={{ left: `${style.x}%`, top: `${style.y}%`, fontSize: style.fontSize, background: style.background ? "rgba(0,0,0,.72)" : "transparent" }}>{active}</div>}
                <button className="fullscreenButton" type="button" onClick={toggleFullscreen} disabled={exporting} aria-label={isFullscreen ? "Exit fullscreen" : "Open fullscreen editor"}>
                  {isFullscreen ? "✕ Exit" : "⛶ Full Screen"}
                </button>
              </div>
              <div className="languagePicker">
                <label htmlFor="caption-language">Caption language</label>
                <select id="caption-language" value={language} onChange={(e) => { setLanguage(e.target.value); setSegments([]); setStatus(""); }} disabled={busy || exporting}>
                  {LANGUAGES.map((item) => <option key={item.code} value={item.code}>{item.label}</option>)}
                </select>
                <small>Auto Detect keeps the language spoken in the video. Other options translate it.</small>
              </div>
              <div className="controls">
                <button className="primary" disabled={busy || exporting} onClick={transcribe}>{busy ? (uploadProgress ? `Uploading ${Math.round(uploadProgress)}%…` : "Gemini is processing…") : `Generate ${selectedLanguage} captions`}</button>
                {segments.length > 0 && <button disabled={exporting} onClick={exportCaptionedVideo}>{exporting ? "Rendering video…" : "Download Video + Text"}</button>}
                {segments.length > 0 && <button disabled={exporting} onClick={downloadSrt}>Download SRT</button>}
                <button disabled={busy || exporting} onClick={() => { setVideo(null); setSegments([]); setUrl(""); setStatus(""); }}>Change video</button>
              </div>
              {segments.length > 0 && <div className="editor">
                <h3>Edit caption position & style</h3>
                <p>Drag the caption directly on the video preview. The same position is used in the exported video.</p>
                <label>Size <input type="range" min="18" max="54" value={style.fontSize} onChange={(e) => setStyle({ ...style, fontSize: +e.target.value })} /></label>
                <label><input type="checkbox" checked={style.background} onChange={(e) => setStyle({ ...style, background: e.target.checked })} /> Background</label>
                <button onClick={() => setStyle({ ...style, x: 50, y: 84 })}>Reset position</button>
              </div>}
              <p className="status">{status}</p>
            </>
          )}
        </div>
      </section>
      <section className="features">
        <div><b>01</b><h3>Direct large-video upload</h3><p>Your browser uploads directly to Vercel Blob instead of sending the video through the Vercel Function request body.</p></div>
        <div><b>02</b><h3>Gemini Files API</h3><p>Gemini receives the uploaded video through its Files API, which is better suited to larger video inputs.</p></div>
        <div><b>03</b><h3>Video + SRT export</h3><p>Download a burned-in captioned WebM video or a standard UTF-8 SRT subtitle file.</p></div>
      </section>
      <footer>CaptionAI • Gemini API key stays on the server.</footer>
    </main>
  );
}
